# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'masterMind.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1426, 1236)
        MainWindow.setMinimumSize(QtCore.QSize(0, 350))
        MainWindow.setStyleSheet("QFrame {\n"
"    border: none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 140))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.title = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.gridLayout_3.addWidget(self.title, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.menu = QtWidgets.QWidget()
        self.menu.setObjectName("menu")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.menu)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_3 = QtWidgets.QFrame(self.menu)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(478, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(538, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        self.table_global = QtWidgets.QTableWidget(self.frame_3)
        self.table_global.setMaximumSize(QtCore.QSize(16777215, 80))
        self.table_global.setRowCount(1)
        self.table_global.setColumnCount(4)
        self.table_global.setObjectName("table_global")
        item = QtWidgets.QTableWidgetItem()
        self.table_global.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_global.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_global.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_global.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_global.setHorizontalHeaderItem(3, item)
        self.gridLayout_2.addWidget(self.table_global, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_2.addItem(spacerItem3, 3, 0, 1, 1)
        self.table_career = QtWidgets.QTableWidget(self.frame_3)
        self.table_career.setRowCount(6)
        self.table_career.setColumnCount(6)
        self.table_career.setObjectName("table_career")
        self.gridLayout_2.addWidget(self.table_career, 4, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_3, 2, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.menu)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.text_color = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.text_color.setFont(font)
        self.text_color.setObjectName("text_color")
        self.verticalLayout_2.addWidget(self.text_color)
        self.Box_color = QtWidgets.QComboBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Box_color.setFont(font)
        self.Box_color.setObjectName("Box_color")
        self.Box_color.addItem("")
        self.Box_color.addItem("")
        self.Box_color.addItem("")
        self.Box_color.addItem("")
        self.Box_color.addItem("")
        self.verticalLayout_2.addWidget(self.Box_color)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.text_cases = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.text_cases.setFont(font)
        self.text_cases.setObjectName("text_cases")
        self.verticalLayout_3.addWidget(self.text_cases)
        self.Box_cases = QtWidgets.QComboBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Box_cases.setFont(font)
        self.Box_cases.setObjectName("Box_cases")
        self.Box_cases.addItem("")
        self.Box_cases.addItem("")
        self.Box_cases.addItem("")
        self.Box_cases.addItem("")
        self.Box_cases.addItem("")
        self.verticalLayout_3.addWidget(self.Box_cases)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.text_repetition = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.text_repetition.setFont(font)
        self.text_repetition.setObjectName("text_repetition")
        self.verticalLayout.addWidget(self.text_repetition)
        self.Box_repetition = QtWidgets.QComboBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Box_repetition.setFont(font)
        self.Box_repetition.setObjectName("Box_repetition")
        self.Box_repetition.addItem("")
        self.Box_repetition.addItem("")
        self.verticalLayout.addWidget(self.Box_repetition)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PlayButton = QtWidgets.QPushButton(self.frame_2)
        self.PlayButton.setMinimumSize(QtCore.QSize(0, 0))
        self.PlayButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.PlayButton.setFont(font)
        self.PlayButton.setStyleSheet("padding-left: 50px;\n"
"padding-right: 50px;\n"
"padding-top: 10px;\n"
"padding-bottom: 10px;")
        self.PlayButton.setObjectName("PlayButton")
        self.horizontalLayout_2.addWidget(self.PlayButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 0, 2, 2, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_4.addItem(spacerItem5, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(1174, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame_2, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 120, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_5.addItem(spacerItem7, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.menu)
        self.option = QtWidgets.QWidget()
        self.option.setObjectName("option")
        self.stackedWidget.addWidget(self.option)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1426, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Master Mind"))
        self.label.setText(_translate("MainWindow", "Statistics"))
        item = self.table_global.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Global"))
        item = self.table_global.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Games played"))
        item = self.table_global.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Victory"))
        item = self.table_global.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Difficulty"))
        item = self.table_global.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Gameplay"))
        self.text_color.setText(_translate("MainWindow", "Number of colors"))
        self.Box_color.setItemText(0, _translate("MainWindow", "4"))
        self.Box_color.setItemText(1, _translate("MainWindow", "6"))
        self.Box_color.setItemText(2, _translate("MainWindow", "8"))
        self.Box_color.setItemText(3, _translate("MainWindow", "10"))
        self.Box_color.setItemText(4, _translate("MainWindow", "12"))
        self.text_cases.setText(_translate("MainWindow", "Number of cases"))
        self.Box_cases.setItemText(0, _translate("MainWindow", "4"))
        self.Box_cases.setItemText(1, _translate("MainWindow", "6"))
        self.Box_cases.setItemText(2, _translate("MainWindow", "8"))
        self.Box_cases.setItemText(3, _translate("MainWindow", "10"))
        self.Box_cases.setItemText(4, _translate("MainWindow", "12"))
        self.text_repetition.setText(_translate("MainWindow", "Repetition"))
        self.Box_repetition.setItemText(0, _translate("MainWindow", "Activate"))
        self.Box_repetition.setItemText(1, _translate("MainWindow", "Deactivate"))
        self.PlayButton.setText(_translate("MainWindow", "Play"))
